### ISSUE TITLE
had to install previous version as v0.5.0 has lost ctrl+alt+p functionality...

### ISSUE THREAD

**Issue by andrekos** [kukushi/PasteURL#12]
...command not found error... back to 0.4.4 and all works fine as before

**Comment by eduardseifert** [comment]
Same here.

Error message: Command 'Paste URL' resulted in an error (command 'extension.pasteURL' not found)
Visual Studio Code: v1.46.1
Paste URL: v0.5.0

**Comment by kukushi** [comment]
Sorry for any inconvenience. As a workaround, I had rollback to 0.4.4.

**Comment by akosma** [comment]
Same with 0.5.1.

**Comment by kukushi** [comment]
After some trial and error, turned out it's the `node_modules` which added to the `.vscodeignore`  broken the command.
It's now fixed.
