### ISSUE TITLE
Add a reference to markdown-link-expander

### ISSUE THREAD

**Issue by iaeiou** [kukushi/PasteURL#15]
Hi there,

thanks for your awesome extension, I'm using it every day

I recently discovered another complementary extension: https://github.com/Skn0tt/markdown-link-expander

Maybe you want to add a reference in your Readme?

**Comment by kukushi** [comment]
> Hi there,
> 
> thanks for your awesome extension, I'm using it every day
> 
> I recently discovered another complementary extension: https://github.com/Skn0tt/markdown-link-expander
> 
> Maybe you want to add a reference in your Readme?

I would love to. Thx.
