### ISSUE TITLE
Drag and Drop from Workspace Explorer.

### ISSUE THREAD

**Issue by AceTheWiz** [kukushi/PasteURL#3]
Would it be possible to add functionality to drag and drop "files" from the Workspace. When the "file" is dropped in the markdown file it converts it to a markdown link. Files would be Markdown files or image files.

e.g. if this is the file path F:\Projects\Evaluating\DevDocs\Docsify\docs\Plans\Development.md
the root of the workspace is docs then the link will look like this
[Development](Plans/Development.md)

**Comment by kukushi** [comment]
Technically speaking, It's possible to add support for local markdown files. Previously, I tried to implement that but it requires some time.
Drag and drop image files is, IMO, out of the scope.

**Comment by kukushi** [comment]
OK. After doing some research, I found the VSCode has not yet open the "drag and drop" API. 
I would recommand you using the Typora which implemented what you want.
