### ISSUE TITLE
Don't paste characters in title as html encoded

### ISSUE THREAD

**Issue by devgid** [kukushi/PasteURL#41]
If I paste for vscode marketplace this extension I get the following:

[Paste&#32;URL&#32;-&#32;Visual&#32;Studio&#32;Marketplace](https://marketplace.visualstudio.com/items?itemName=kukushi.pasteurl)
The above link shows correct in preview but in edit view shows as following:

![image](https://github.com/kukushi/PasteURL/assets/13977449/054722da-9362-4a9a-bc6c-6199a48c3a27)

The htmll encoded characters in the title should be removed and replaced with reading display characters.

**Comment by kukushi** [comment]
Thanks for your reporting. The issues has been resolved in 0.5.6.
