### ISSUE TITLE
fails with YouTube

### ISSUE THREAD

**Issue by Yzrsah** [kukushi/PasteURL#5]
Hello. Awesome extension. But we are using YouTube to do some research and it does not work with URL pasting!

All URL's pasted from YouTube fail to work correctly and have no information except "YouTube" in the title.

**Comment by kukushi** [comment]
It seems that Youtube simply put "Youtube" in their html title.

**Comment by Zyrsha** [comment]
For YouTube it's just:
"http://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=" + vid + "&format=json"
The returned JSON contains the title.

It is only a few lines of code to add this, you probably have a preferred way of altering your code to deal with i.e. processSpecialURL()

I threw it in as a quick hack

**Comment by Zyrsha** [comment]
For YouTube it's just:
`"http://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=" + vid + "&format=json"`
The returned JSON contains the title.

It is only a few lines of code to add this, you probably have a preferred way of altering your code to deal with i.e. processSpecialURL()

I threw it in as a quick hack

**Comment by Yzrsah** [comment]
SuperPasteURL closes this issue.
The recommendation is to switch to SuperPasteURL instead of PasteURL

https://github.com/alincode/SuperPasteURL
https://marketplace.visualstudio.com/items?itemName=alincode.SuperPasteURL

**Comment by Yzrsah** [comment]
SuperPasteURL closes this issue.

https://github.com/alincode/SuperPasteURL
https://marketplace.visualstudio.com/items?itemName=alincode.SuperPasteURL
